### ISSUE TITLE
Add support for favorite 

### ISSUE THREAD

**Issue by singhsaubhik** [SinghSaubhik/CryptoKeep#16]
Add favorite in login model and should be saved in DB as well, user should be able to favorite, unfavorite the login from login details screen.

**Comment by KirbyNguyen** [comment]
If you haven't implemented this yet, I can take a look at this!

**Comment by singhsaubhik** [comment]
> If you haven't implemented this yet, I can take a look at this!

Sure, go ahead, see the implementation of `category`
@KirbyNguyen
